'use client';

import { useState } from 'react';
import { Copy, Server, MessageCircle, ExternalLink } from 'lucide-react';

const AGENT_TEMPLATES = [
  {
    id: 'general',
    name: 'Claw-General',
    handle: 'claw_general',
    emoji: '🔧',
    description: 'Coordinator, strategy, system design',
    tags: 'general, strategy, coordination',
    droplet_size: 's-1vcpu-1gb',
    cost: 6
  },
  {
    id: 'dev',
    name: 'Claw-Dev',
    handle: 'claw_dev',
    emoji: '💻',
    description: 'Code, infrastructure, APIs',
    tags: 'coding, infrastructure, devops',
    droplet_size: 's-1vcpu-2gb',
    cost: 12
  },
  {
    id: 'research',
    name: 'Claw-Research',
    handle: 'claw_research',
    emoji: '📊',
    description: 'Due diligence, market analysis',
    tags: 'research, analysis, due_diligence',
    droplet_size: 's-1vcpu-1gb',
    cost: 6
  },
  {
    id: 'finance',
    name: 'Claw-Finance',
    handle: 'claw_finance',
    emoji: '💰',
    description: 'Fundraising, cap tables, modeling',
    tags: 'finance, fundraising, modeling',
    droplet_size: 's-1vcpu-1gb',
    cost: 6
  },
  {
    id: 'ops',
    name: 'Claw-Ops',
    handle: 'claw_ops',
    emoji: '⚡',
    description: 'Project management, execution',
    tags: 'operations, project_management',
    droplet_size: 's-1vcpu-1gb',
    cost: 6
  },
  {
    id: 'mining',
    name: 'Claw-Mining',
    handle: 'claw_mining',
    emoji: '⛏️',
    description: 'Mining, geology, tenements',
    tags: 'mining, geology, tenements, processing',
    droplet_size: 's-1vcpu-1gb',
    cost: 6
  }
];

export function AgentDropletProvisioner() {
  const [runnerToken, setRunnerToken] = useState('');
  const [generatedScripts, setGeneratedScripts] = useState<Record<string, string>>({});
  const [selectedAgent, setSelectedAgent] = useState<string | null>(null);

  const generateCloudInit = (agent: typeof AGENT_TEMPLATES[0]) => {
    return `#!/bin/bash
# Claw Agent: ${agent.name}
# Generated by Fleet Manager

apt-get update
apt-get install -y python3-pip python3-venv git curl

mkdir -p /opt/claw-agent
cd /opt/claw-agent

python3 -m venv venv
source venv/bin/activate

pip install httpx pyyaml python-telegram-bot

curl -fsSL https://raw.githubusercontent.com/AyrtonMansi/openclaw-fleet/main/runner/runner.py -o runner.py

cat > /opt/claw-agent/config.yaml << 'EOF'
control_plane_url: https://fleet.amansi.com.au/api
runner_token: "${runnerToken}"

agents:
  - name: "${agent.name}"
    handle: "${agent.handle}"
    model: gpt-4
    tags: [${agent.tags}]
    max_concurrency: 2
    telegram:
      bot_token: "PASTE_BOT_TOKEN_HERE"
      bot_username: "${agent.handle}_bot"
EOF

cat > /etc/systemd/system/claw-agent.service << 'EOF'
[Unit]
Description=${agent.name} Agent
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/claw-agent
ExecStart=/opt/claw-agent/venv/bin/python /opt/claw-agent/runner.py
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable claw-agent
systemctl start claw-agent

echo "${agent.name} Agent installed!"
`;
  };

  const generateAll = () => {
    const scripts: Record<string, string> = {};
    AGENT_TEMPLATES.forEach(agent => {
      scripts[agent.id] = generateCloudInit(agent);
    });
    setGeneratedScripts(scripts);
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
  };

  const totalCost = AGENT_TEMPLATES.reduce((acc, a) => acc + a.cost, 0);

  return (
    <div className="bg-white rounded-xl border border-gray-200 p-5">
      <div className="flex items-center gap-2 mb-4">
        <Server className="w-5 h-5 text-indigo-500" />
        <h3 className="font-semibold text-gray-900">Claw Team Provisioner</h3>
      </div>

      <p className="text-sm text-gray-600 mb-4">
        Deploy 6 specialized Claw agents, each on their own DigitalOcean droplet.
        Each has its own Telegram bot for direct communication.
      </p>

      {/* Runner Token */}
      <div className="mb-4">
        <label className="block text-sm font-medium text-gray-700 mb-1">
          Runner Token from Fleet Manager
        </label>
        <input
          type="text"
          value={runnerToken}
          onChange={(e) => setRunnerToken(e.target.value)}
          placeholder="Paste token from Settings → Runner Tokens"
          className="w-full px-3 py-2 border border-gray-300 rounded-lg"
        />
      </div>

      {/* Cost Summary */}
      <div className="p-3 bg-gray-50 rounded-lg mb-4">
        <div className="flex items-center justify-between text-sm">
          <span className="text-gray-600">Total Team Cost:</span>
          <span className="font-semibold text-lg">${totalCost}/month</span>
        </div>
        <p className="text-xs text-gray-500 mt-1">
          6 droplets × $6-12/mo each
        </p>
      </div>

      {/* Agent List */}
      <div className="space-y-2 mb-4">
        {AGENT_TEMPLATES.map((agent) => (
          <div
            key={agent.id}
            className={`p-3 border rounded-lg cursor-pointer transition-colors ${
              selectedAgent === agent.id
                ? 'border-indigo-500 bg-indigo-50'
                : 'border-gray-200 hover:border-gray-300'
            }`}
            onClick={() => setSelectedAgent(agent.id)}
          >
            <div className="flex items-center gap-3">
              <span className="text-2xl">{agent.emoji}</span>
              <div className="flex-1">
                <p className="font-medium">{agent.name}</p>
                <p className="text-sm text-gray-500">@{agent.handle}_bot</p>
              </div>
              <div className="text-right">
                <p className="text-sm font-medium">${agent.cost}/mo</p>
                <p className="text-xs text-gray-400">{agent.droplet_size}</p>
              </div>
            </div>
            <p className="text-sm text-gray-600 mt-2 ml-11">{agent.description}</p>
          </div>
        ))}
      </div>

      {/* Generate Button */}
      <button
        onClick={generateAll}
        disabled={!runnerToken}
        className="w-full py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 disabled:opacity-50"
      >
        Generate Cloud-Init Scripts
      </button>

      {/* Generated Scripts */}
      {Object.keys(generatedScripts).length > 0 && (
        <div className="mt-4 space-y-3">
          <h4 className="font-medium text-gray-900">Cloud-Init Scripts</h4>
          
          {AGENT_TEMPLATES.map((agent) => (
            <div key={agent.id} className="border border-gray-200 rounded-lg overflow-hidden">
              <div className="flex items-center justify-between p-3 bg-gray-50">
                <div className="flex items-center gap-2">
                  <span>{agent.emoji}</span>
                  <span className="font-medium text-sm">{agent.name}</span>
                </div>
                <button
                  onClick={() => copyToClipboard(generatedScripts[agent.id])}
                  className="flex items-center gap-1 text-sm text-blue-600 hover:text-blue-700"
                >
                  <Copy className="w-4 h-4" />
                  Copy
                </button>
              </div>
              {selectedAgent === agent.id && (
                <pre className="p-3 bg-gray-900 text-gray-100 text-xs overflow-x-auto max-h-40">
                  {generatedScripts[agent.id]}
                </pre>
              )}
            </div>
          ))}

          {/* Instructions */}
          <div className="p-4 bg-indigo-50 rounded-lg text-sm text-indigo-800">
            <p className="font-medium mb-2">Next Steps:</p>
            <ol className="list-decimal list-inside space-y-1">
              <li>Create Telegram bots with @BotFather (6 bots)</li>
              <li>For each agent, create a DO droplet (Ubuntu 22.04)</li>
              <li>Paste the cloud-init script in User Data</li>
              <li>Replace "PASTE_BOT_TOKEN_HERE" in the config</li>
              <li>SSH in and restart: systemctl restart claw-agent</li>
            </ol>
            <a
              href="https://github.com/AyrtonMansi/openclaw-fleet/blob/main/agents/SETUP_GUIDE.md"
              target="_blank"
              className="inline-flex items-center gap-1 mt-3 text-indigo-600 hover:underline"
            >
              <ExternalLink className="w-4 h-4" />
              Full Setup Guide
            </a>
          </div>
        </div>
      )}
    </div>
  );
}
